### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by bgelfand** [Tengyun-Mo/buildLibrealsense2TX2#1]
For those of you who run into the issue of "command not found" when attempting to execute 
`$ ./buildPatchedKernel.sh`, `chmod -R +x '/pathto/buildLibrealsense2TX2'` will resolve the issue. The problem is that the scripts in the directory are not executable by default on a fresh install, even if it's run as super user. 

@Tengyun-Mo Should I do a pull request to add it to the README.md or would you prefer to not add it?

**Comment by Tengyun-Mo** [comment]
It's a common-sense issue,I think others will solve this by themselves.
