### ISSUE TITLE
which file to patch for this command?

### ISSUE THREAD

**Issue by jaiatncson7** [Tengyun-Mo/buildLibrealsense2TX2#2]
jetson@jetson-desktop:~/buildLibrealsense2TX2$ ./patchApplication.sh 
Applying Model-Views Patch
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/common/model-views.cpp b/common/model-views.cpp
|index eaeac779..ad246523 100644
|--- a/common/model-views.cpp
|+++ b/common/model-views.cpp
--------------------------
File to patch: 

Can you help what is the file name have to be given here?

**Comment by doublestrong** [comment]
According to the notes in the patch files, I open the files to be fixed in the librealsense directory and modify them manually and then recompile librealsense.

**Comment by jaiatncson7** [comment]
Yes i fixed it thanks.
